from typing import Dict, List, Protocol, runtime_checkable


@runtime_checkable
class BrokerProtocol(Protocol):
    is_connected: bool
    account_number: str | None
    simulation_mode: bool

    def connect(self, account_number: str) -> bool: ...
    def disconnect(self) -> bool: ...
    def get_account_info(self) -> Dict: ...
    def place_order(self, code: str, quantity: int, price: float, order_type: str) -> str: ...
    def cancel_order(self, order_id: str) -> bool: ...
    def get_order_status(self, order_id: str) -> Dict: ...
    def get_stock_quote(self, code: str) -> Dict: ...
    def get_daily_chart(self, code: str, days: int) -> List[Dict]: ...
    def get_broker_info(self) -> Dict: ...
