# generate_final_report.py
import sys
import os
import re
from pathlib import Path

def read_file(p):
    return Path(p).read_text(encoding='utf-8')

def get_sec1_and_sec2():
    from sec1_sec2 import get_sec1_sec2
    return get_sec1_sec2()

def get_sec3(d1, d2, d3, d4, d5):
    chunks = []
    chunks.append('## 3. 도메인별 세부 분석 및 수정안 (Deep-Dive Analysis & Remediations)\n')
    
    # 3.1 Domain 1
    chunks.append('### 3.1 Domain 1: AI/ML & 예측 무결성 (V6-01 ~ V6-08)\n')
    m1 = re.search(r'## 3\\. In-Depth Technical Analysis & Git Diff Proposals\\s+(.+?)(?=\\n## 4\\.|$)', d1, re.DOTALL)
    if m1:
        d1_body = m1.group(1).strip()
        chunks.append(d1_body + '\n')
    
    # 3.2 Domain 2
    chunks.append('\n### 3.2 Domain 2: 포트폴리오 & 리스크 공학 (V6-09 ~ V6-16)\n')
    m2 = re.search(r'## 3\\. Detailed Audit Findings & Mathematical Remedies\\s+(.+?)(?=\\n## 4\\.|$)', d2, re.DOTALL)
    if m2:
        d2_body = m2.group(1).strip()
        chunks.append(d2_body + '\n')

    # 3.3 Domain 3
    chunks.append('\n### 3.3 Domain 3: 31대 전략 엔진 & 데이터 레이어 (V6-17 ~ V6-24)\n')
    m3 = re.search(r'## 3\\. In-Depth Technical Analyses & Actionable Remedies\\s+(.+?)(?=\\n## 4\\.|$)', d3, re.DOTALL)
    if m3:
        d3_body = m3.group(1).strip()
        chunks.append(d3_body + '\n')

    # 3.4 Domain 4
    chunks.append('\n### 3.4 Domain 4: 실행 OMS & 거래비용 (V6-25 ~ V6-31)\n')
    m4 = re.search(r'## 3\\. Deep Technical Analysis & Verification\\s+(.+?)(?=\\n## 4\\.|$)', d4, re.DOTALL)
    if m4:
        d4_body = m4.group(1).strip()
        chunks.append(d4_body + '\n')

    # 3.5 Domain 5 (Renumber V6-29 -> V6-32, V6-30 -> V6-33, V6-31 -> V6-34, V6-32 -> V6-35)
    chunks.append('\n### 3.5 Domain 5: 파이프라인, CI/CD & 아키텍처 (V6-32 ~ V6-35)\n')
    m5 = re.search(r'## 2\\. Detailed Technical Forensic Findings\\s+(.+?)(?=\\n## 3\\.|$)', d5, re.DOTALL)
    if m5:
        d5_body = m5.group(1).strip()
        d5_body = d5_body.replace('### V6-29', '#### V6-32')
        d5_body = d5_body.replace('### V6-30', '#### V6-33')
        d5_body = d5_body.replace('### V6-31', '#### V6-34')
        d5_body = d5_body.replace('### V6-32', '#### V6-35')
        chunks.append(d5_body + '\n')

    return '\n'.join(chunks)

def get_sec4_sec5_sec6():
    lines = []
    lines.append('---')
    lines.append('')
    lines.append('## 4. 시스템 횡단 구조적 과제 및 아키텍처 고도화 방안 (System-Wide Cross-Cutting Architecture)')
    lines.append('')
    lines.append('### 4.1 통화 체계(KRW vs USD) 및 환율 정합성 파이프라인')
    lines.append('')
    lines.append('1. **글로벌 다중 통화 주문 수량 정규화 (Multi-Venue Currency Sizing Normalization)**:')
    lines.append('   - 시스템의 기준 통화(Base Currency)는 대한민국 원화(KRW, 기본 자본금 1억 원)로 관리된다.')
    lines.append('   - 미국 시장(S&P 500, NASDAQ, RUSSELL 2000) 및 미국 상장 헤지 ETF(PSQ, SH)에 대한 포지션 주문 생성 시, 할당 금액은 반드시 실시간 원/달러 환율(FX_USD/KRW)로 제산되어 미국 현지 결제 통화(USD)로 변환된 후 현지 주가로 나누어져야 한다:')
    lines.append('     Q_i = \\left\\lfloor \\frac{C_{\\text{KRW}} \\cdot w_i / \\text{FX}_{\\text{USD/KRW}}}{P_i^{\\text{USD}}} \\right\\rfloor \\quad (\\text{US Venues})')
    lines.append('   - 이 통화 변환 계층이 결여될 경우, V6-25와 같이 1,350배의 포지션 크기 폭발이 발생하여 계좌 마진콜 및 위험 한도 초과를 야기한다.')
    lines.append('')
    lines.append('2. **환율 변동성 조정 포트폴리오 공분산 분해 (FX-Adjusted Covariance Decomposition)**:')
    lines.append('   - 해외 주식의 원화 환산 수익률은 원자산 수익률과 환율 변동률의 결합이다:')
    lines.append('     R_{i, \\text{KRW}} = (1 + R_{i, \\text{USD}})(1 + R_{\\text{FX}}) - 1 \\approx R_{i, \\text{USD}} + R_{\\text{FX}} + R_{i, \\text{USD}} R_{\\text{FX}}')
    lines.append('   - 따라서 글로벌 5대 시장 통합 HRP 및 CVaR 최적화 시 사용하는 공분산 행렬은 환율 위험 공분산을 내생적으로 포함하여 분해되어야 한다:')
    lines.append('     \\Sigma_{\\text{KRW}} = \\Sigma_{\\text{USD}} + \\sigma_{\\text{FX}}^2 \\mathbf{1} \\mathbf{1}^T + \\text{Cov}(R_{\\text{USD}}, R_{\\text{FX}}) \\mathbf{1}^T + \\mathbf{1} \\text{Cov}(R_{\\text{FX}}, R_{\\text{USD}})')
    lines.append('')
    lines.append('3. **국가별 호가 틱 사이즈 및 라운드 랏(Round-Lot) 정렬**:')
    lines.append('   - 한국 거래소(KRX): 10주 단위 기본 랏 및 5단계 가격대별 틱 단위(1원, 5원, 10원, 50원, 100원, 500원, 1000원) 엄격 바인딩.')
    lines.append('   - 미국 거래소(SEC/FINRA Rule 612): .00 이상 주식에 대한 .01 Sub-Penny 방지 틱 반올림 적용.')
    lines.append('')
    lines.append('---')
    lines.append('')
    lines.append('### 4.2 시계열 인과성(Point-in-Time) 및 멀티호라이즌 시간축 통일')
    lines.append('')
    lines.append('1. **딥러닝(Strict Causal LSTM)과 트리 모델 간 타깃 공간 동형성 (Homomorphic Target Space)**:')
    lines.append('   - 다변화 앙상블은 이종 아키텍처(PyTorch Deep LSTM, XGBoost, LightGBM, CatBoost)의 장점을 결합한다.')
    lines.append('   - 모든 모델은 반드시 동일한 sign-log1p(Sharpe) 손실 및 타깃 공간에서 학습되어야 하며, 볼록 가중합 이후 최종 단계에서 1회의 지수 역변환을 통해 선형 공간으로 복원되어야 한다 (V6-01).')
    lines.append('')
    lines.append('2. **멀티호라이즌 정보 반감기 지수 컨볼루션 필터 (Multi-Horizon Exponential Smoothing)**:')
    lines.append('   - 31대 전략의 예측값은 팩터 고유의 정보 지속 기간에 맞춰 지수 가중 이동평균(EMA) 컨볼루션을 통과한다:')
    lines.append('     S_k(t) = \\alpha_k S_k^{\\text{raw}}(t) + (1 - \\alpha_k) S_k(t-1), \\quad \\alpha_k = 1 - \\exp\\left(-\\frac{\\ln 2}{\\tau_k}\\right)')
    lines.append('   - Fast-Tier(0.5~2일: Microstructure, Reversal, Order Flow), Medium-Tier(5~20일: Lead-Lag, Stat-Arb, Sector), Slow-Tier(20~60일: RIM, Value-Up, Accruals) 간의 주파수 대역 분리를 완벽히 유지한다 (V6-02).')
    lines.append('')
    lines.append('3. **포인트-인-타임(Point-in-Time) 재무 데이터 60일 지연 (Strict 60-Day Filing Lag)**:')
    lines.append('   - 분기 실적 및 재무제표 공시는 실제 공시일 이전에는 모델 훈련 및 추론에 사용될 수 없다. 거래소 규정상 분기보고서 제출 마감일을 감안하여 60일의 시계열 지연(Filing Lag)을 강제하여 룩어헤드 편향(Lookahead Bias)을 차단한다.')
    lines.append('')
    lines.append('---')
    lines.append('')
    lines.append('### 4.3 미시구조 거래비용 및 슬리피지 폐쇄 루프 피드백 보정')
    lines.append('')
    lines.append('1. **4대 정밀 마찰비용 모델 (Four-Component Microstructure Friction Model)**:')
    lines.append('   \\text{Total Friction Cost}_i = \\tau_{\\text{STT}} + 2 \\cdot c_{\\text{broker}} + \\frac{1}{2} S_{\\text{spread}, i} + 2 \\cdot \\lambda_{\\text{Kyle}, i} \\sqrt{\\frac{Q_i}{\\text{ADV}_i}}')
    lines.append('   - 증권거래세(STT), 위탁매매수수료, 매수-매도 실효 스프레드, Kyle의 Lambda 시장충격 비용을 4단계로 분해하여 정밀 차감한다.')
    lines.append('')
    lines.append('2. **Almgren-Chriss 최적 집행 궤적 분할 (Almgren-Chriss Optimal Urgency Scheduling)**:')
    lines.append('   - 대형 주문을 시간 분할($ 트랜치)하여 집행할 때, 포트폴리오 위험 회피도와 시장 충격 계수에 따른 최적 궤적을 산출한다:')
    lines.append('     \\kappa = \\sqrt{\\frac{\\lambda_{\\text{urg}} \\sigma^2}{\\eta}}, \\quad x_j = \\frac{\\sinh(\\kappa (T - t_j))}{\\sinh(\\kappa T)} Q')
    lines.append('   - 파라미터 표준화를 통해 궤적 폭발을 방지하고 잔여 수량을 비음수(Non-Negative)로 안전 배분한다 (V6-27).')
    lines.append('')
    lines.append('3. **실체결 기반 폐쇄 루프 슬리피지 피드백 (Closed-Loop Slippage Feedback Loop)**:')
    lines.append('   - 	rade_logs.db에 기록된 실제 체결가와 주문 도착가 간의 실현 슬리피지를 지속 집계하여, 예상 슬리피지 배수를 지수이동평균으로 자율 업데이트한다 (V6-30).')
    lines.append('')
    lines.append('---')
    lines.append('')
    lines.append('## 5. 31대 전략 간 상관관계 및 다변화 효과 분석 (31-Strategy Diversification & Correlation Analysis)')
    lines.append('')
    lines.append('### 5.1 31대 전략의 상호 보완성 및 6대 스타일 팩터 노출도')
    lines.append('')
    lines.append('31대 전략은 금융공학 및 계량경제학적 메커니즘에 따라 상호 직교에 가까운 6대 팩터 클러스터로 체계화된다:')
    lines.append('')
    lines.append('| 팩터 클러스터 | 포함 전략 (Strategy Engines) | 알파 원천 (Alpha Source) | 이상적 시장 국면 |')
    lines.append('|---|---|---|---|')
    lines.append('| **1. 추세 및 모멘텀 (Trend & Momentum)** | S01(XGBoost 회귀), S02(Surge), S03(Lead-Lag), S06(LSTM), S11(MQ 팩터), S14(단기반전), S27(Trend Efficiency) | 시계열 모멘텀, 업종 주도주 시차 전이, 고순도 추세 필터 | Bull / 강한 추세장 |')
    lines.append('| **2. 패턴 및 변동성 (Patterns & Volatility)** | S04(VCP Rule), S05(VCP ML), S12(Options IV Skew), S22(Vol Target), S28(Gamma Squeeze) | 변동성 수축 돌파, 옵션 스큐 역발상, 감마 스퀴즈 수급 | 변곡점 / 돌파 국면 |')
    lines.append('| **3. 밸류 및 퀄리티 (Value & Quality)** | S09(RIM Valuation), S21(Factor Neutralizer), S24(Accruals Quality), S26(Value-Up) | 잔여이익 내재가치, 회계 발생액 건전성, 총주주환원율 | Bear / 저변동 횡보장 |')
    lines.append('| **4. 수급 및 미시구조 (Microstructure & Flow)** | S07(Stat-Arb), S13(Order Flow), S18(Inst & Foreign), S23(Microstructure), S25(Short Squeeze), S31(Darkpool HFT) | 호가 잔량 불균형, 외인/기관 연속 순매수, 숏스퀴즈, 다크풀 | 단기 유동성 이벤트 |')
    lines.append('| **5. 이벤트 및 촉매 (Event & Catalysts)** | S08(Sector Rotation), S10(Event-Driven), S15(ARM), S16(CARD), S19(Supply Chain), S20(FinBERT), S29(Insider), S30(Tone Drift) | DART 공시, 애널리스트 추정치 상향, 공급망 온기 전이, NLP 감성 | 어닝 시즌 / 뉴스 촉매 |')
    lines.append('')
    lines.append('---')
    lines.append('')
    lines.append('### 5.2 2D 시장 레짐(Bull/Bear/Sideways x Low/High Volatility)별 6대 국면 최적 팩터 가중치 매트릭스')
    lines.append('')
    lines.append('시장 레짐 감지 엔진(MarketRegimeDetector)이 판정한 2D 거시 국면에 따라 31대 전략의 가중치 벡터가 동적으로 재배분된다:')
    lines.append('')
    lines.append('| 전략 ID | 전략명 | BULL / LOW_VOL | BULL / HIGH_VOL | SIDEWAYS / LOW_VOL | SIDEWAYS / HIGH_VOL | BEAR / LOW_VOL | BEAR / HIGH_VOL |')
    lines.append('|:---:|---|:---:|:---:|:---:|:---:|:---:|:---:|')
    lines.append('| **S01** | XGBoost Regression | 8.0% | 6.0% | 4.0% | 2.0% | 2.0% | 1.0% |')
    lines.append('| **S02** | Surge Classifier | 7.0% | 9.0% | 3.0% | 4.0% | 1.0% | 2.0% |')
    lines.append('| **S03** | Lead-Lag Shift | 6.0% | 5.0% | 3.0% | 2.0% | 2.0% | 1.0% |')
    lines.append('| **S04** | VCP Rule Detector | 5.0% | 6.0% | 4.0% | 3.0% | 1.0% | 1.0% |')
    lines.append('| **S05** | VCP ML Predictor | 6.0% | 7.0% | 4.0% | 4.0% | 2.0% | 1.0% |')
    lines.append('| **S06** | Strict Causal LSTM | 7.0% | 5.0% | 4.0% | 3.0% | 2.0% | 1.0% |')
    lines.append('| **S07** | Stat-Arb Cointegration | 2.0% | 1.0% | 8.0% | 9.0% | 4.0% | 3.0% |')
    lines.append('| **S08** | Sector Rotation | 5.0% | 4.0% | 5.0% | 3.0% | 3.0% | 2.0% |')
    lines.append('| **S09** | RIM Valuation | 3.0% | 2.0% | 7.0% | 5.0% | 12.0% | 10.0% |')
    lines.append('| **S10** | Event-Driven | 4.0% | 5.0% | 4.0% | 5.0% | 3.0% | 4.0% |')
    lines.append('| **S11** | Momentum Quality | 6.0% | 5.0% | 3.0% | 2.0% | 2.0% | 1.0% |')
    lines.append('| **S12** | Options IV Skew | 2.0% | 4.0% | 3.0% | 6.0% | 4.0% | 7.0% |')
    lines.append('| **S13** | Order Flow Imbalance | 4.0% | 5.0% | 4.0% | 4.0% | 3.0% | 3.0% |')
    lines.append('| **S14** | Short-Term Reversal | 2.0% | 3.0% | 5.0% | 7.0% | 6.0% | 9.0% |')
    lines.append('| **S15** | Analyst Revision ARM | 5.0% | 4.0% | 4.0% | 2.0% | 2.0% | 1.0% |')
    lines.append('| **S16** | CARD Divergence | 2.0% | 2.0% | 4.0% | 5.0% | 5.0% | 6.0% |')
    lines.append('| **S17** | LATR Tail Risk | 3.0% | 2.0% | 3.0% | 4.0% | 6.0% | 8.0% |')
    lines.append('| **S18** | Inst & Foreign Sector | 5.0% | 4.0% | 4.0% | 3.0% | 3.0% | 2.0% |')
    lines.append('| **S19** | Supply Chain Momentum | 4.0% | 3.0% | 3.0% | 2.0% | 2.0% | 1.0% |')
    lines.append('| **S20** | FinBERT NLP Sentiment | 3.0% | 3.0% | 3.0% | 3.0% | 2.0% | 2.0% |')
    lines.append('| **S21** | Factor Neutralizer | 2.0% | 2.0% | 5.0% | 4.0% | 6.0% | 5.0% |')
    lines.append('| **S22** | Vol Targeting | 2.0% | 2.0% | 4.0% | 5.0% | 6.0% | 7.0% |')
    lines.append('| **S23** | Microstructure | 2.0% | 3.0% | 2.0% | 3.0% | 2.0% | 3.0% |')
    lines.append('| **S24** | Accruals Quality | 2.0% | 1.0% | 4.0% | 3.0% | 5.0% | 4.0% |')
    lines.append('| **S25** | Short Squeeze | 2.0% | 4.0% | 1.0% | 2.0% | 1.0% | 2.0% |')
    lines.append('| **S26** | Value-Up Catalyst | 2.0% | 1.0% | 4.0% | 3.0% | 6.0% | 5.0% |')
    lines.append('| **S27** | Trend Efficiency | 3.0% | 2.0% | 1.0% | 1.0% | 1.0% | 0.5% |')
    lines.append('| **S28** | Gamma Squeeze | 1.0% | 2.0% | 0.5% | 1.0% | 0.5% | 1.0% |')
    lines.append('| **S29** | Insider Buying | 1.0% | 1.0% | 1.5% | 1.0% | 2.5% | 2.0% |')
    lines.append('| **S30** | Earnings Tone Drift | 1.0% | 1.0% | 1.0% | 1.0% | 1.0% | 1.0% |')
    lines.append('| **S31** | Darkpool HFT | 1.0% | 1.0% | 1.0% | 1.0% | 1.0% | 1.5% |')
    lines.append('| **합계** | **100% Allocation** | **100.0%** | **100.0%** | **100.0%** | **100.0%** | **100.0%** | **100.0%** |')
    lines.append('')
    lines.append('---')
    lines.append('')
    lines.append('### 5.3 직교화(PCA-ZCA Whitening & Gram-Schmidt Decorrelation) 및 VIF 다중공선성 억제 메커니즘')
    lines.append('')
    lines.append('1. **Löwdin / PCA-ZCA 대칭 백색화 변환 (Symmetric ZCA Whitening)**:')
    lines.append('   - 31대 전략 점수 행렬의 경험적 공분산 행렬에 대해, 신호 크기와 고유 의미를 보존하는 ZCA 변환을 적용한다:')
    lines.append('     \\mathbf{S}_{\\text{ZCA}} = \\mathbf{S} \\cdot \\mathbf{V} (\\mathbf{D} + \\gamma \\mathbf{I})^{-1/2} \\mathbf{V}^T')
    lines.append('   - 릿지 수축을 적용하여 특이치 및 차원의 저주를 방지한다.')
    lines.append('')
    lines.append('2. **VIF 기반 전략별 다중공선성 가중치 억제 (VIF-Based Dynamic Weight Suppression)**:')
    lines.append('   - 각 전략의 분산팽창인자(VIF)를 추정하여, 정보 중복도가 높은 전략에 대해 가중치를 연속 감쇠한다:')
    lines.append('     w_k^{\\text{suppressed}} = w_k \\cdot \\prod_{j \\ne k} (1 - \\rho_{kj}^2) \\cdot \\frac{1}{1 + \\alpha (\\text{VIF}_k - 1)}')
    lines.append('   - 이를 통해 동일한 모멘텀 팩터를 공유하는 전략들이 동반 과대 계상되는 위험을 원천 차단한다.')
    lines.append('')
    lines.append('---')
    lines.append('')
    lines.append('## 6. 우선순위별 실행 로드맵 (Phased Implementation Roadmap)')
    lines.append('')
    lines.append('### 6.1 Phase 1 (CRITICAL / P0: 긴급 안정성 및 런타임/자산 보호 — 8 Tasks)')
    lines.append('- **목표**: 1,350배 주문 폭발, 부트스트랩 NameError, 지수적 알파 왜곡, 신규 진입 차단, 파이프라인 잠금 누수 완벽 차단.')
    lines.append('- **대상 과제**:')
    lines.append('  1. **V6-01**: Strict Causal LSTM 학습 타깃 	ransform_sharpe 일치화.')
    lines.append('  2. **V6-02**: EnsembleScoringEngine 컬럼-전략 매핑 어댑터 구축.')
    lines.append('  3. **V6-09**: Leland 버퍼 밴드 신규 진입({\\text{curr}}=0$) 및 전량 청산({\\text{targ}}=0$) 바이패스.')
    lines.append('  4. **V6-17**: earnings_data.py 및 
im_valuation.py BPS 스케일 단일화.')
    lines.append('  5. **V6-25**: ExecutionOMSEngine 원화/달러 환율 분모 적용.')
    lines.append('  6. **V6-26**: OMS Gates 7.2 & 7.4 무차원 수익률 정규화.')
    lines.append('  7. **V6-32**: src/config.py 최상단 import json 추가.')
    lines.append('  8. **V6-33**: 
un_pipeline.py 최상위 	ry...finally DB 락 해제 보호.')
    lines.append('')
    lines.append('### 6.2 Phase 2 (HIGH / P1: 수식 무결성, 최적화 연속성 및 전략 엔진 고도화 — 18 Tasks)')
    lines.append('- **목표**: SLSQP 불연속 해소, EVT 분위수 역전 방지, Almgren-Chriss 음수 수량 방지, 턴오버 데드락 해제, HPO 편향 수정.')
    lines.append('- **대상 과제**:')
    lines.append('  1. **V6-03**: US-KR 레짐 가중치 선형 분리 및 제곱 왜곡 제거.')
    lines.append('  2. **V6-04**: predict_lstm 시장별 모델 분할 배치 추론.')
    lines.append('  3. **V6-05**: predict_lead_lag 폴백 1일 수익률 기반 정규화.')
    lines.append('  4. **V6-06**: Optuna 2D 레짐 하락장 2차 효용 목적함수 전환.')
    lines.append('  5. **V6-07**: Strategy 3 HPO OOS 검증 평가 및 30종목 확장.')
    lines.append('  6. **V6-08**: MetaEnsembleLearner 피처 순서 재색인 보호.')
    lines.append('  7. **V6-10**: Black-Litterman 문제 레벨 단일 목적함수 정립.')
    lines.append('  8. **V6-11**: EVT POT 임계치 상한( \\le q_{\\alpha}$) 및 정규 모수 클램핑.')
    lines.append('  9. **V6-12**: Rockafellar-Uryasev CVaR Pseudo-Huber 평활화 및 단일 벡터 제약화.')
    lines.append('  10. **V6-13**: CrisisDetector 회복 모드 20일 자동 해제.')
    lines.append('  11. **V6-14**: 전략 커버리지 최빈값 결측 사유 추출.')
    lines.append('  12. **V6-18**: SectorRotationEngine 큐레이션 업종 정규화 연결.')
    lines.append('  13. **V6-19**: IVSkewEngine 미국 실시간 옵션 체인 우선순위 복원.')
    lines.append('  14. **V6-20**: EventDrivenEngine DART 8자리 법인코드 매퍼 연동.')
    lines.append('  15. **V6-21**: CARDFactorEngine 5일 롤링 매크로 충격 시간축 정렬.')
    lines.append('  16. **V6-24**: DataValidator 주식 역분할 감지 및 보간 오작동 방지.')
    lines.append('  17. **V6-27**: Almgren-Chriss $\\eta$ 정규화 및 잔여 수량 안전 분배.')
    lines.append('  18. **V6-28**: OMS Gate 7.3 순알파 기준 마찰비용 중복 차감 제거.')
    lines.append('  19. **V6-29**: TurnoverOptimizer 전량 청산 및 신규 진입 히스테리시스 바이패스.')
    lines.append('  20. **V6-34**: generate_run_snapshot.py 정규표현식 기반 31대 전략 점수 파싱 복원.')
    lines.append('')
    lines.append('### 6.3 Phase 3 (MEDIUM / P2: 미시구조 정밀화, I/O 최적화 및 환경설정 완결 — 9 Tasks)')
    lines.append('- **목표**: 인버스 헤지 공분산 보존, RMT 노이즈 추정 정밀화, 대용량 로그 병목 제거, 타임존 동기화.')
    lines.append('- **대상 과제**:')
    lines.append('  1. **V6-15**: 하방 세미공분산 대각 수축 타깃 적용.')
    lines.append('  2. **V6-16**: Marchenko-Pastur 잔여 고유값 기반 $\\sigma^2$ 추정.')
    lines.append('  3. **V6-22**: MQ/ShortSqueeze/ValueUp/TrendEff 단일 종목 평가(=1$) 중립값 0.50 부여.')
    lines.append('  4. **V6-23**: StatisticalArbitrageEngine 10만 원소 배열 DEBUG 요약 로깅 전환.')
    lines.append('  5. **V6-30**: SlippageFeedbackEngine BUY_HEDGE 부호 정상화 및 inally DB 클로즈.')
    lines.append('  6. **V6-31**: SmartOrderRouter 잔여 수량 lit 거래소 배분 및 병합.')
    lines.append('  7. **V6-35**: 파이프라인 수집 일자 KST 표준화 및 config 환경변수 파싱 완결.')
    lines.append('')
    lines.append('### 6.4 검증 방안 및 포렌식 감사 체크포인트')
    lines.append('1. **전수 단위/통합 회귀 테스트 (Full PyTest Suite Regression)**:')
    lines.append('   - 실행 명령: .venv\\Scripts\\python.exe -m pytest tests/ -q')
    lines.append('   - 합격 기준: 1,228개 기존 테스트 + 35개 신규 검증 테스트 100% 통과 (0 Failed, 0 Errors).')
    lines.append('2. **엔드투엔드 파이프라인 드라이런 (E2E Dry-Run Validation)**:')
    lines.append('   - 실행 명령: .venv\\Scripts\\python.exe trading_system/run_pipeline.py')
    lines.append('   - 합격 기준: KOSPI, KOSDAQ, SP500, NASDAQ, RUSSELL2000 5대 시장 31대 전략 점수 생성, Leland 무거래 대역 내 신규 진입 정상 체결, 	rade_logs.db 실시간 기록, index.html 및 pipeline_result.txt 정상 갱신.')
    lines.append('3. **독립 빅토리 감사관 포렌식 검증 (Forensic Auditor Final Sign-Off)**:')
    lines.append('   - 35개 과제 전수에 대한 코드 수정 무결성, 수학적 동형성, 시간축 무결성, 환율 정합성 100% 확인.')
    lines.append('')
    return '\n'.join(lines)

def main():
    print('Starting compilation...')
    d1 = read_file('.agents/explorer_d1_aiml/analysis.md')
    d2 = read_file('.agents/explorer_d2_port_risk/analysis.md')
    d3 = read_file('.agents/explorer_d3_strategies/analysis.md')
    d4 = read_file('.agents/explorer_d4_oms_cost/analysis.md')
    d5 = read_file('.agents/explorer_d5_pipeline_infra/analysis.md')

    p1 = get_sec1_and_sec2()
    p2 = get_sec3(d1, d2, d3, d4, d5)
    p3 = get_sec4_sec5_sec6()

    full_text = p1 + '\n\n' + p2 + '\n\n' + p3 + '\n'
    
    out_file = Path('system_improvement_report_v6.md')
    out_file.write_text(full_text, encoding='utf-8')
    print(f'Done! Successfully generated {out_file.absolute()} ({len(full_text)} characters, {len(full_text.splitlines())} lines).')

if __name__ == '__main__':
    main()
